<script lang="ts">
	/**
	 * /lab — Scene Lab.
	 *
	 * Admin-gated tuning UI for the ModelScene three.js engine. Holds ONE
	 * deeply-reactive SceneConfig in $state; every knob binds straight into
	 * it and <ModelScene {config}> live-applies changes itself (the engine
	 * watches the config via its own $effect — no per-knob plumbing here).
	 *
	 * "Copy as code" dumps the current config as a paste-ready snippet for
	 * src/lib/three/heroConfig.ts. Presets live in localStorage under
	 * 'pxp-lab:presets' with a factory seed on first visit.
	 */
	import { onMount } from 'svelte';
	import ModelScene from '$lib/three/ModelScene.svelte';
	import {
		DEFAULT_SCENE_CONFIG,
		cloneConfig,
		type SceneConfig,
		type DirectionalLightConfig
	} from '$lib/three/types';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	// ─── The single source of truth ────────────────────────────────────────
	let config = $state<SceneConfig>(cloneConfig(DEFAULT_SCENE_CONFIG));

	// ─── Loading overlay ────────────────────────────────────────────────────
	// Shown until the engine fires onReady (which also fires on load failure).
	// A 12s fallback guards against the callback never arriving.
	let sceneLoading = $state(true);

	// ─── Panel collapse (button + H key) ────────────────────────────────────
	let panelOpen = $state(true);

	function onKeydown(e: KeyboardEvent) {
		if (e.key !== 'h' && e.key !== 'H') return;
		const t = e.target as HTMLElement | null;
		if (t) {
			const tag = t.tagName;
			if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT' || t.isContentEditable) {
				return;
			}
		}
		panelOpen = !panelOpen;
	}

	// ─── Model path (dropdown + free-text alternative) ──────────────────────
	let customPath = $state('');

	let isCustomPath = $derived(
		config.model.path !== null && !data.models.includes(config.model.path)
	);

	function onModelSelect(e: Event) {
		const v = (e.currentTarget as HTMLSelectElement).value;
		config.model.path = v === '' ? null : v;
		customPath = v;
	}

	function applyCustomPath() {
		const trimmed = customPath.trim();
		config.model.path = trimmed === '' ? null : trimmed;
	}

	// ─── Presets (localStorage) ──────────────────────────────────────────────
	const PRESET_KEY = 'pxp-lab:presets';

	let presets = $state<Record<string, SceneConfig>>({});
	let presetName = $state('');
	let saveFlash = $state(false);

	let presetNames = $derived(Object.keys(presets).sort());

	function loadPresetsFromStorage() {
		try {
			const raw = window.localStorage.getItem(PRESET_KEY);
			if (raw) {
				presets = JSON.parse(raw);
			} else {
				// First visit only: seed a factory preset so the list is never
				// empty. Never re-injected — deleting it sticks.
				presets = { 'P&P Default': cloneConfig(DEFAULT_SCENE_CONFIG) };
				writePresetsToStorage();
			}
		} catch (e) {
			console.warn('[lab] could not load presets', e);
		}
	}

	function writePresetsToStorage() {
		try {
			window.localStorage.setItem(PRESET_KEY, JSON.stringify(presets));
		} catch (e) {
			console.warn('[lab] could not save presets', e);
		}
	}

	function savePreset() {
		const name = presetName.trim();
		if (!name) return;
		// Clone on save so later knob edits never mutate the stored preset.
		presets = { ...presets, [name]: cloneConfig(config) };
		writePresetsToStorage();
		saveFlash = true;
		setTimeout(() => (saveFlash = false), 1200);
	}

	function loadPreset(name: string) {
		const p = presets[name];
		if (!p) return;
		// Clone on load so knob edits never mutate the stored preset either.
		config = cloneConfig(p);
		customPath = config.model.path ?? '';
		presetName = name;
	}

	function deletePreset(name: string) {
		if (!confirm(`Delete preset "${name}"?`)) return;
		const { [name]: _drop, ...rest } = presets;
		void _drop;
		presets = rest;
		writePresetsToStorage();
	}

	// ─── Copy as code ────────────────────────────────────────────────────────
	let copied = $state(false);

	function buildSnippet(): string {
		const json = JSON.stringify(cloneConfig(config), null, '\t');
		return `// Generated by /lab — paste into src/lib/three/heroConfig.ts\nexport const HERO_SCENE_CONFIG: SceneConfig = ${json};\n`;
	}

	async function copyAsCode() {
		try {
			await navigator.clipboard.writeText(buildSnippet());
			copied = true;
			setTimeout(() => (copied = false), 1500);
		} catch (e) {
			console.warn('[lab] clipboard write failed', e);
		}
	}

	// ─── Reset ───────────────────────────────────────────────────────────────
	function resetAll() {
		config = cloneConfig(DEFAULT_SCENE_CONFIG);
		customPath = config.model.path ?? '';
	}

	onMount(() => {
		loadPresetsFromStorage();
		const loadFallback = setTimeout(() => (sceneLoading = false), 12000);
		return () => clearTimeout(loadFallback);
	});
</script>

<svelte:head>
	<title>Scene Lab // Parallax&amp;Pixel</title>
	<meta name="robots" content="noindex, nofollow" />
</svelte:head>

<svelte:window onkeydown={onKeydown} />

<!-- Full-screen scene background. The engine live-applies config changes. -->
<div class="scene-bg" aria-hidden="true">
	<ModelScene {config} onReady={() => (sceneLoading = false)} />
</div>

{#if sceneLoading}
	<div class="scene-loading">
		<p class="scene-loading-text font-terminal">
			loading scene...<span class="cursor" aria-hidden="true">█</span>
		</p>
	</div>
{/if}

<button
	type="button"
	class="panel-toggle font-terminal"
	onclick={() => (panelOpen = !panelOpen)}
	aria-label={panelOpen ? 'Hide panel' : 'Show panel'}
>
	{panelOpen ? '→' : '←'}
</button>

{#if panelOpen}
	<aside class="lab-panel" aria-label="Scene Lab controls">
		<header class="panel-head">
			<h1 class="title font-display">Scene Lab</h1>
			<div class="hint font-terminal">press <kbd>H</kbd> to hide</div>
		</header>

		<!-- ── Model ── -->
		<section class="group">
			<h2 class="font-terminal">Model</h2>
			<label class="row">
				<span>file</span>
				<select class="select" value={config.model.path ?? ''} onchange={onModelSelect}>
					<option value="">(procedural fallback)</option>
					{#each data.models as model (model)}
						<option value={model}>{model}</option>
					{/each}
					{#if isCustomPath}
						<option value={config.model.path}>{config.model.path} (custom)</option>
					{/if}
				</select>
				<output></output>
			</label>
			<div class="row" style="grid-template-columns: 1fr auto;">
				<input
					type="text"
					class="text-input"
					bind:value={customPath}
					placeholder="/models/your-model.glb"
					onkeydown={(e) => e.key === 'Enter' && applyCustomPath()}
				/>
				<button type="button" class="btn-ghost btn-small" onclick={applyCustomPath}>Load</button>
			</div>
			<p class="hint-row">drop .glb/.gltf/.obj/.fbx files into static/models/ and reload</p>

			<label class="row">
				<span>scale</span>
				<input type="range" min="0.05" max="8" step="0.01" bind:value={config.model.scale} />
				<output>{config.model.scale.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>x</span>
				<input type="range" min="-5" max="5" step="0.05" bind:value={config.model.x} />
				<output>{config.model.x.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>y</span>
				<input type="range" min="-5" max="5" step="0.05" bind:value={config.model.y} />
				<output>{config.model.y.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>z</span>
				<input type="range" min="-5" max="5" step="0.05" bind:value={config.model.z} />
				<output>{config.model.z.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>rot x</span>
				<input type="range" min="-3.1416" max="3.1416" step="0.01" bind:value={config.model.rotationX} />
				<output>{config.model.rotationX.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>rot y</span>
				<input type="range" min="-3.1416" max="3.1416" step="0.01" bind:value={config.model.rotationY} />
				<output>{config.model.rotationY.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>rot z</span>
				<input type="range" min="-3.1416" max="3.1416" step="0.01" bind:value={config.model.rotationZ} />
				<output>{config.model.rotationZ.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>spin speed</span>
				<input type="range" min="-2" max="2" step="0.01" bind:value={config.model.spinSpeed} />
				<output>{config.model.spinSpeed.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>float amp</span>
				<input type="range" min="0" max="1" step="0.005" bind:value={config.model.floatAmplitude} />
				<output>{config.model.floatAmplitude.toFixed(3)}</output>
			</label>
			<label class="row">
				<span>float speed</span>
				<input type="range" min="0" max="4" step="0.01" bind:value={config.model.floatSpeed} />
				<output>{config.model.floatSpeed.toFixed(2)}</output>
			</label>
		</section>

		<!-- ── Lights ── -->
		{#snippet dirLight(label: string, light: DirectionalLightConfig)}
			<div class="sub">
				<label class="row toggle">
					<input type="checkbox" bind:checked={light.on} />
					<span class="label">{label}</span>
				</label>
				<label class="row">
					<span>intensity</span>
					<input type="range" min="0" max="3" step="0.01" bind:value={light.intensity} />
					<output>{light.intensity.toFixed(2)}</output>
				</label>
				<label class="row">
					<span>color</span>
					<input type="color" bind:value={light.color} />
					<code>{light.color}</code>
				</label>
				<label class="row">
					<span>x</span>
					<input type="range" min="-15" max="15" step="0.1" bind:value={light.x} />
					<output>{light.x.toFixed(1)}</output>
				</label>
				<label class="row">
					<span>y</span>
					<input type="range" min="-15" max="15" step="0.1" bind:value={light.y} />
					<output>{light.y.toFixed(1)}</output>
				</label>
				<label class="row">
					<span>z</span>
					<input type="range" min="-15" max="15" step="0.1" bind:value={light.z} />
					<output>{light.z.toFixed(1)}</output>
				</label>
			</div>
		{/snippet}

		<section class="group">
			<h2 class="font-terminal">Lights</h2>
			{@render dirLight('Key', config.lights.key)}
			{@render dirLight('Rim', config.lights.rim)}
			{@render dirLight('Fill', config.lights.fill)}

			<div class="sub">
				<label class="row toggle">
					<input type="checkbox" bind:checked={config.lights.ambient.on} />
					<span class="label">Ambient</span>
				</label>
				<label class="row">
					<span>intensity</span>
					<input type="range" min="0" max="1.5" step="0.01" bind:value={config.lights.ambient.intensity} />
					<output>{config.lights.ambient.intensity.toFixed(2)}</output>
				</label>
				<label class="row">
					<span>color</span>
					<input type="color" bind:value={config.lights.ambient.color} />
					<code>{config.lights.ambient.color}</code>
				</label>
			</div>
		</section>

		<!-- ── Material ── -->
		<section class="group">
			<h2 class="font-terminal">Material</h2>
			<label class="row toggle">
				<input type="checkbox" bind:checked={config.material.override} />
				<span class="label">override imported materials</span>
			</label>
			<label class="row" class:disabled={!config.material.override}>
				<span>type</span>
				<select class="select" bind:value={config.material.type} disabled={!config.material.override}>
					<option value="standard">standard (PBR)</option>
					<option value="physical">physical (PBR+)</option>
					<option value="basic">basic (unlit)</option>
					<option value="lambert">lambert</option>
					<option value="phong">phong</option>
					<option value="normal">normal (debug)</option>
					<option value="toon">toon</option>
				</select>
				<output></output>
			</label>
			<label class="row" class:disabled={!config.material.override}>
				<span>base color</span>
				<input type="color" bind:value={config.material.baseColor} disabled={!config.material.override} />
				<code>{config.material.baseColor}</code>
			</label>
			<label class="row" class:disabled={!config.material.override}>
				<span>metalness</span>
				<input type="range" min="0" max="1" step="0.01" bind:value={config.material.metalness} disabled={!config.material.override} />
				<output>{config.material.metalness.toFixed(2)}</output>
			</label>
			<label class="row" class:disabled={!config.material.override}>
				<span>roughness</span>
				<input type="range" min="0" max="1" step="0.01" bind:value={config.material.roughness} disabled={!config.material.override} />
				<output>{config.material.roughness.toFixed(2)}</output>
			</label>
			<label class="row" class:disabled={!config.material.override}>
				<span>opacity</span>
				<input type="range" min="0" max="1" step="0.01" bind:value={config.material.opacity} disabled={!config.material.override} />
				<output>{config.material.opacity.toFixed(2)}</output>
			</label>
			<label class="row" class:disabled={!config.material.override}>
				<span>emissive</span>
				<input type="color" bind:value={config.material.emissiveColor} disabled={!config.material.override} />
				<code>{config.material.emissiveColor}</code>
			</label>
			<label class="row" class:disabled={!config.material.override}>
				<span>emissive int</span>
				<input type="range" min="0" max="3" step="0.01" bind:value={config.material.emissiveIntensity} disabled={!config.material.override} />
				<output>{config.material.emissiveIntensity.toFixed(2)}</output>
			</label>
			<label class="row toggle" class:disabled={!config.material.override}>
				<input type="checkbox" bind:checked={config.material.wireframe} disabled={!config.material.override} />
				<span class="label">wireframe</span>
			</label>
			<label class="row toggle" class:disabled={!config.material.override}>
				<input type="checkbox" bind:checked={config.material.flatShading} disabled={!config.material.override} />
				<span class="label">flat shading</span>
			</label>
			<p class="hint-row">override off = the model keeps its own imported materials</p>
		</section>

		<!-- ── Fresnel ── -->
		<section class="group">
			<h2 class="font-terminal">Fresnel rim</h2>
			<label class="row toggle">
				<input type="checkbox" bind:checked={config.fresnel.on} />
				<span class="label">enabled</span>
			</label>
			<label class="row toggle">
				<input type="checkbox" bind:checked={config.fresnel.drift} />
				<span class="label">auto aqua↔mint drift</span>
			</label>
			<label class="row" class:disabled={config.fresnel.drift}>
				<span>color</span>
				<input type="color" bind:value={config.fresnel.color} disabled={config.fresnel.drift} />
				<code>{config.fresnel.color}</code>
			</label>
			<label class="row">
				<span>power</span>
				<input type="range" min="0.5" max="16" step="0.1" bind:value={config.fresnel.power} />
				<output>{config.fresnel.power.toFixed(1)}</output>
			</label>
			<label class="row" class:disabled={config.fresnel.drift}>
				<span>strength</span>
				<input type="range" min="0" max="3" step="0.01" bind:value={config.fresnel.strength} disabled={config.fresnel.drift} />
				<output>{config.fresnel.strength.toFixed(2)}</output>
			</label>
			<p class="hint-row">drift sweeps color + strength over time while on</p>
		</section>

		<!-- ── Post ── -->
		<section class="group">
			<h2 class="font-terminal">Post-processing</h2>

			<div class="sub">
				<label class="row toggle">
					<input type="checkbox" bind:checked={config.post.bloom.on} />
					<span class="label">Bloom</span>
				</label>
				<label class="row">
					<span>strength</span>
					<input type="range" min="0" max="3" step="0.01" bind:value={config.post.bloom.strength} />
					<output>{config.post.bloom.strength.toFixed(2)}</output>
				</label>
				<label class="row">
					<span>radius</span>
					<input type="range" min="0" max="2" step="0.01" bind:value={config.post.bloom.radius} />
					<output>{config.post.bloom.radius.toFixed(2)}</output>
				</label>
				<label class="row">
					<span>threshold</span>
					<input type="range" min="0" max="1" step="0.01" bind:value={config.post.bloom.threshold} />
					<output>{config.post.bloom.threshold.toFixed(2)}</output>
				</label>
			</div>

			<div class="sub">
				<label class="row toggle">
					<input type="checkbox" bind:checked={config.post.vignette.on} />
					<span class="label">Vignette</span>
				</label>
				<label class="row">
					<span>offset</span>
					<input type="range" min="0" max="2" step="0.01" bind:value={config.post.vignette.offset} />
					<output>{config.post.vignette.offset.toFixed(2)}</output>
				</label>
				<label class="row">
					<span>darkness</span>
					<input type="range" min="0" max="2" step="0.01" bind:value={config.post.vignette.darkness} />
					<output>{config.post.vignette.darkness.toFixed(2)}</output>
				</label>
			</div>

			<div class="sub">
				<label class="row toggle">
					<input type="checkbox" bind:checked={config.post.chromaticAberration.on} />
					<span class="label">Chromatic aberration</span>
				</label>
				<label class="row">
					<span>offset</span>
					<input type="range" min="0" max="0.01" step="0.0001" bind:value={config.post.chromaticAberration.offset} />
					<output>{config.post.chromaticAberration.offset.toFixed(4)}</output>
				</label>
			</div>

			<div class="sub">
				<label class="row toggle">
					<input type="checkbox" bind:checked={config.post.noise.on} />
					<span class="label">Noise</span>
				</label>
				<label class="row">
					<span>opacity</span>
					<input type="range" min="0" max="0.5" step="0.005" bind:value={config.post.noise.opacity} />
					<output>{config.post.noise.opacity.toFixed(3)}</output>
				</label>
			</div>
		</section>

		<!-- ── Camera ── -->
		<section class="group">
			<h2 class="font-terminal">Camera</h2>
			<label class="row">
				<span>fov</span>
				<input type="range" min="18" max="90" step="0.5" bind:value={config.camera.fov} />
				<output>{config.camera.fov.toFixed(1)}</output>
			</label>
			<label class="row">
				<span>x</span>
				<input type="range" min="-10" max="10" step="0.05" bind:value={config.camera.x} />
				<output>{config.camera.x.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>y</span>
				<input type="range" min="-5" max="10" step="0.05" bind:value={config.camera.y} />
				<output>{config.camera.y.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>z (distance)</span>
				<input type="range" min="1" max="24" step="0.05" bind:value={config.camera.z} />
				<output>{config.camera.z.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>target y</span>
				<input type="range" min="-5" max="5" step="0.05" bind:value={config.camera.targetY} />
				<output>{config.camera.targetY.toFixed(2)}</output>
			</label>
			<label class="row toggle">
				<input type="checkbox" bind:checked={config.camera.parallax.on} />
				<span class="label">mouse parallax</span>
			</label>
			<label class="row" class:disabled={!config.camera.parallax.on}>
				<span>amount</span>
				<input type="range" min="0" max="2" step="0.01" bind:value={config.camera.parallax.amount} disabled={!config.camera.parallax.on} />
				<output>{config.camera.parallax.amount.toFixed(2)}</output>
			</label>
			<label class="row" class:disabled={!config.camera.parallax.on}>
				<span>ease</span>
				<input type="range" min="0.005" max="0.3" step="0.005" bind:value={config.camera.parallax.ease} disabled={!config.camera.parallax.on} />
				<output>{config.camera.parallax.ease.toFixed(3)}</output>
			</label>
		</section>

		<!-- ── Renderer ── -->
		<section class="group">
			<h2 class="font-terminal">Renderer</h2>
			<label class="row">
				<span>pixel ratio</span>
				<input type="range" min="0.5" max="3" step="0.05" bind:value={config.renderer.pixelRatio} />
				<output>{config.renderer.pixelRatio.toFixed(2)}</output>
			</label>
			<label class="row">
				<span>tone map</span>
				<select class="select" bind:value={config.renderer.toneMapping}>
					<option value="none">none</option>
					<option value="linear">linear</option>
					<option value="reinhard">reinhard</option>
					<option value="cineon">cineon</option>
					<option value="aces">aces filmic</option>
				</select>
				<output></output>
			</label>
			<label class="row">
				<span>exposure</span>
				<input type="range" min="0" max="3" step="0.01" bind:value={config.renderer.exposure} />
				<output>{config.renderer.exposure.toFixed(2)}</output>
			</label>
			<label class="row toggle">
				<input type="checkbox" bind:checked={config.renderer.transparent} />
				<span class="label">transparent canvas</span>
			</label>
			<label class="row" class:disabled={config.renderer.transparent}>
				<span>clear color</span>
				<input type="color" bind:value={config.renderer.clearColor} disabled={config.renderer.transparent} />
				<code>{config.renderer.clearColor}</code>
			</label>
			<p class="hint-row">clear color only applies when transparent is off</p>
		</section>

		<!-- ── Presets ── -->
		<section class="group">
			<h2 class="font-terminal">Presets</h2>
			<div class="row" style="grid-template-columns: 1fr auto;">
				<input
					type="text"
					class="text-input"
					bind:value={presetName}
					placeholder="preset name"
					onkeydown={(e) => e.key === 'Enter' && savePreset()}
				/>
				<button type="button" class="btn-ghost btn-small" onclick={savePreset}>
					{saveFlash ? '✓' : 'Save'}
				</button>
			</div>
			{#if presetNames.length === 0}
				<p class="hint-row">no presets saved yet</p>
			{:else}
				<ul class="preset-list">
					{#each presetNames as name (name)}
						<li class="preset-row">
							<button type="button" class="preset-load font-terminal" onclick={() => loadPreset(name)}>
								{name}
							</button>
							<button
								type="button"
								class="preset-del"
								aria-label="Delete {name}"
								onclick={() => deletePreset(name)}>×</button
							>
						</li>
					{/each}
				</ul>
			{/if}
		</section>

		<!-- ── Actions ── -->
		<section class="actions">
			<button type="button" class="btn-primary font-terminal" onclick={copyAsCode}>
				{copied ? 'Copied ✓' : 'Copy as code'}
			</button>
			<button type="button" class="btn-ghost font-terminal" onclick={resetAll}>Reset all</button>
		</section>
	</aside>
{/if}

<style>
	.scene-bg {
		position: fixed;
		inset: 0;
		z-index: 0;
	}

	/* ── Loading overlay — covers everything until the model is painted ── */
	.scene-loading {
		position: fixed;
		inset: 0;
		z-index: 200;
		display: flex;
		align-items: center;
		justify-content: center;
		background: #020617;
	}
	.scene-loading-text {
		margin: 0;
		font-size: 0.9rem;
		letter-spacing: 0.08em;
		color: #00a5cf;
	}
	.cursor {
		display: inline-block;
		margin-left: 0.2em;
		color: #9fffcb;
		animation: blink 1s steps(1) infinite;
	}
	@keyframes blink {
		0%,
		49% {
			opacity: 1;
		}
		50%,
		100% {
			opacity: 0;
		}
	}

	/* ── Panel toggle ── */
	.panel-toggle {
		position: fixed;
		top: 5rem;
		right: 1rem;
		z-index: 60;
		background: rgba(2, 6, 23, 0.9);
		color: #00a5cf;
		border: 1px solid rgba(0, 165, 207, 0.45);
		font-size: 1rem;
		width: 2.25rem;
		height: 2.25rem;
		cursor: pointer;
		display: grid;
		place-items: center;
	}
	.panel-toggle:hover {
		border-color: #9fffcb;
		color: #9fffcb;
	}

	/* ── Panel shell ── */
	.lab-panel {
		position: fixed;
		top: 0;
		right: 0;
		bottom: 0;
		z-index: 50;
		width: min(420px, 95vw);
		padding: 1rem 1rem 1.5rem;
		background: rgba(2, 6, 23, 0.92);
		border-left: 1px solid rgba(0, 165, 207, 0.35);
		backdrop-filter: blur(10px);
		-webkit-backdrop-filter: blur(10px);
		overflow-y: auto;
		color: #cbd5e1;
		font-size: 0.85rem;
	}

	.panel-head {
		display: flex;
		justify-content: space-between;
		align-items: baseline;
		margin-bottom: 1.25rem;
		padding-bottom: 0.5rem;
		border-bottom: 1px solid rgba(0, 165, 207, 0.25);
	}
	.title {
		margin: 0;
		font-size: 1.35rem;
		color: #e2f6ff;
		letter-spacing: 0.02em;
	}
	.hint {
		font-size: 0.66rem;
		color: #64748b;
		letter-spacing: 0.06em;
	}
	kbd {
		background: rgba(0, 165, 207, 0.15);
		border: 1px solid rgba(0, 165, 207, 0.45);
		padding: 0.05rem 0.35rem;
		font-family: inherit;
		color: #00a5cf;
	}

	/* ── Groups + sub-cards ── */
	.group {
		margin-bottom: 1.5rem;
	}
	.group h2 {
		font-size: 0.72rem;
		font-weight: 700;
		letter-spacing: 0.16em;
		text-transform: uppercase;
		color: #9fffcb;
		margin: 0 0 0.6rem;
		padding-bottom: 0.3rem;
		border-bottom: 1px dashed rgba(37, 161, 142, 0.35);
	}
	.sub {
		margin-bottom: 0.7rem;
		padding: 0.5rem 0.55rem;
		background: rgba(15, 23, 42, 0.6);
		border: 1px solid rgba(0, 165, 207, 0.14);
	}

	/* ── Knob rows ── */
	.row {
		display: grid;
		grid-template-columns: 6rem 1fr 4rem;
		align-items: center;
		gap: 0.5rem;
		padding: 0.18rem 0;
		font-size: 0.8rem;
	}
	.row.toggle {
		grid-template-columns: 1.2rem 1fr;
	}
	.row.disabled {
		opacity: 0.4;
	}
	.row span {
		font-family: 'Space Mono', monospace;
		font-size: 0.66rem;
		text-transform: uppercase;
		letter-spacing: 0.06em;
		color: #94a3b8;
	}
	.row span.label {
		text-transform: none;
		letter-spacing: 0;
		color: #cbd5e1;
		font-size: 0.8rem;
	}
	.row output,
	.row code {
		font-family: 'Space Mono', monospace;
		font-size: 0.68rem;
		color: #00a5cf;
		text-align: right;
	}
	.row input[type='range'] {
		width: 100%;
		accent-color: #00a5cf;
	}
	.row input[type='color'] {
		width: 100%;
		height: 1.3rem;
		border: 1px solid rgba(0, 165, 207, 0.35);
		border-radius: 0;
		background: transparent;
		cursor: pointer;
		padding: 0;
	}
	.row input[type='checkbox'] {
		accent-color: #25a18e;
	}
	.hint-row {
		font-family: 'Space Mono', monospace;
		font-size: 0.64rem;
		color: #64748b;
		margin: 0.4rem 0 0.2rem;
	}

	/* ── Inputs / selects / buttons ── */
	.select {
		background: rgba(15, 23, 42, 0.8);
		border: 1px solid rgba(0, 165, 207, 0.35);
		border-radius: 0;
		color: #cbd5e1;
		font-family: 'Space Mono', monospace;
		font-size: 0.74rem;
		padding: 0.25rem 0.4rem;
		width: 100%;
		cursor: pointer;
	}
	.select:focus {
		outline: none;
		border-color: #9fffcb;
	}
	.select:disabled {
		cursor: default;
	}

	.text-input {
		background: rgba(15, 23, 42, 0.8);
		border: 1px solid rgba(0, 165, 207, 0.35);
		border-radius: 0;
		color: #cbd5e1;
		padding: 0.35rem 0.55rem;
		font-family: 'Space Mono', monospace;
		font-size: 0.76rem;
		width: 100%;
	}
	.text-input:focus {
		outline: none;
		border-color: #9fffcb;
	}

	.actions {
		display: grid;
		grid-template-columns: 1fr auto;
		gap: 0.5rem;
		margin-top: 0.5rem;
		padding-top: 0.75rem;
		border-top: 1px solid rgba(0, 165, 207, 0.25);
	}
	.btn-primary,
	.btn-ghost {
		font-size: 0.74rem;
		letter-spacing: 0.08em;
		text-transform: uppercase;
		padding: 0.6rem 0.85rem;
		cursor: pointer;
		border-radius: 0;
		border: 0;
		transition:
			background 0.2s ease,
			color 0.2s ease,
			border-color 0.2s ease;
	}
	.btn-primary {
		background: #00a5cf;
		color: #020617;
	}
	.btn-primary:hover {
		background: #9fffcb;
	}
	.btn-ghost {
		background: transparent;
		color: #00a5cf;
		border: 1px solid rgba(0, 165, 207, 0.45);
	}
	.btn-ghost:hover {
		border-color: #9fffcb;
		color: #9fffcb;
	}
	.btn-small {
		padding: 0.35rem 0.7rem;
		font-size: 0.68rem;
		font-family: 'Space Mono', monospace;
	}

	/* ── Preset list ── */
	.preset-list {
		list-style: none;
		margin: 0.5rem 0 0;
		padding: 0;
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}
	.preset-row {
		display: grid;
		grid-template-columns: 1fr auto;
		gap: 0.25rem;
	}
	.preset-load {
		background: rgba(15, 23, 42, 0.55);
		border: 1px solid rgba(0, 165, 207, 0.2);
		border-radius: 0;
		color: #cbd5e1;
		font-size: 0.74rem;
		text-align: left;
		padding: 0.4rem 0.55rem;
		cursor: pointer;
	}
	.preset-load:hover {
		border-color: #9fffcb;
		color: #9fffcb;
	}
	.preset-del {
		background: transparent;
		border: 1px solid rgba(0, 165, 207, 0.2);
		border-radius: 0;
		color: #94a3b8;
		font-size: 1rem;
		width: 1.9rem;
		cursor: pointer;
	}
	.preset-del:hover {
		border-color: #ef4444;
		color: #ef4444;
	}
</style>
