// src/lib/three/heroConfig.ts
//
// Live config for the homepage hero's ModelScene.
// Paste output of /lab "Copy as code" here to update the live hero.

import type { SceneConfig } from './types';

// Generated by /lab — tuned 2026-06-06
export const HERO_SCENE_CONFIG: SceneConfig = {
	model: {
		path: null,
		scale: 4.51,
		x: 2.45,
		y: 2.25,
		z: 0,
		rotationX: -0.0016,
		rotationY: -0.0016,
		rotationZ: -0.0016,
		spinSpeed: -0.01,
		floatAmplitude: 0,
		floatSpeed: 0
	},
	lights: {
		key: {
			on: true,
			intensity: 2.99,
			color: '#00a5cf',
			x: -7.7,
			y: 2.2,
			z: 7.6
		},
		rim: {
			on: true,
			intensity: 2.41,
			color: '#9fffcb',
			x: -2.4,
			y: -0.4,
			z: -3.6
		},
		fill: {
			on: true,
			intensity: 3,
			color: '#00ffee',
			x: -9.8,
			y: 0.7,
			z: -2.7
		},
		ambient: {
			on: false,
			intensity: 0,
			color: '#0f172a'
		}
	},
	material: {
		override: true,
		type: 'standard',
		baseColor: '#000000',
		metalness: 0.42,
		roughness: 0.49,
		opacity: 1,
		emissiveColor: '#00a5cf',
		emissiveIntensity: 0.3,
		wireframe: false,
		flatShading: true
	},
	fresnel: {
		on: true,
		color: '#00a5cf',
		power: 4.2,
		strength: 0.8,
		drift: true
	},
	post: {
		bloom: {
			on: true,
			strength: 1.08,
			radius: 0.63,
			threshold: 0.06
		},
		vignette: {
			on: false,
			offset: 0,
			darkness: 0.65
		},
		chromaticAberration: {
			on: true,
			offset: 0
		},
		noise: {
			on: true,
			opacity: 0.26
		}
	},
	camera: {
		fov: 54,
		x: -2.7,
		y: 2.75,
		z: 6.2,
		targetY: -0.4,
		parallax: {
			on: true,
			amount: 0.82,
			ease: 0.11
		}
	},
	renderer: {
		pixelRatio: 0.5,
		toneMapping: 'cineon',
		exposure: 0.62,
		transparent: true,
		clearColor: '#020617'
	}
};
