// src/lib/three/heroConfig.ts
//
// Live config for the homepage hero's ModelScene.
// Paste output of /lab "Copy as code" here to update the live hero.

import type { SceneConfig } from './types';

// Generated by /lab — tuned 2026-06-07 (icosahedron + mint wireframe shell)
export const HERO_SCENE_CONFIG: SceneConfig = {
	model: {
		path: null,
		shape: 'icosahedron',
		wireframeShell: {
			on: true,
			color: '#9fffcb',
			opacity: 1,
			scale: 1.13,
			x: -0.01,
			y: 0,
			z: 0,
			rotationX: 0,
			rotationY: 0,
			rotationZ: 0,
			spinSpeed: -0.28,
			floatAmplitude: 0,
			floatSpeed: 0
		},
		scale: 2.25,
		x: 0.95,
		y: 1.3,
		z: 0.35,
		rotationX: -0.0016,
		rotationY: -0.0016,
		rotationZ: -0.0016,
		spinSpeed: 0.03,
		floatAmplitude: 0.11,
		floatSpeed: 0.43
	},
	lights: {
		key: {
			on: true,
			intensity: 1.45,
			color: '#00a5cf',
			x: -8,
			y: 6,
			z: 6
		},
		rim: {
			on: true,
			intensity: 1.41,
			color: '#9fffcb',
			x: 4,
			y: 2,
			z: -6
		},
		fill: {
			on: false,
			intensity: 0.77,
			color: '#25a18e',
			x: 8,
			y: 1.3,
			z: -4.5
		},
		ambient: {
			on: true,
			intensity: 0.12,
			color: '#0f172a'
		}
	},
	material: {
		override: true,
		type: 'physical',
		baseColor: '#0b1220',
		metalness: 0.4,
		roughness: 0.6,
		opacity: 1,
		emissiveColor: '#00a5cf',
		emissiveIntensity: 0.2,
		wireframe: false,
		flatShading: false
	},
	fresnel: {
		on: true,
		color: '#00a5cf',
		power: 3.7,
		strength: 1.58,
		drift: false
	},
	post: {
		bloom: {
			on: true,
			strength: 2,
			radius: 0.35,
			threshold: 0.06
		},
		vignette: {
			on: false,
			offset: 0,
			darkness: 2
		},
		chromaticAberration: {
			on: false,
			offset: 0.0015
		},
		noise: {
			on: false,
			opacity: 0
		}
	},
	overlay: {
		on: true,
		color: '#020617',
		opacity: 0.71,
		gradient: {
			on: true,
			from: '#000000',
			to: '#00708f',
			angle: 192
		},
		vignette: {
			on: true,
			strength: 1,
			size: 57
		},
		scanlines: {
			on: true,
			opacity: 0.11,
			scale: 7
		}
	},
	camera: {
		fov: 47,
		x: 0,
		y: 0.8,
		z: 8.3,
		targetY: -0.65,
		parallax: {
			on: true,
			amount: 0.22,
			ease: 0.23
		}
	},
	renderer: {
		pixelRatio: 1.5,
		toneMapping: 'aces',
		exposure: 1,
		transparent: true,
		clearColor: '#020617'
	}
};
