// DAEDALUS PDF export — builds a multi-page A4 explainer (cover scene image +
// one page per layer panel) and renders it with Playwright (headless Chromium).
// The client (DaedalusStudio) captures the composited scene PNG and sends it
// alongside the marked-rendered panel HTML. Admin-only.
import { chromium } from 'playwright';
import { error, type RequestHandler } from '@sveltejs/kit';
import { resolveChromiumPath } from '$lib/server/chromium-path';
import { requireAdmin } from '$lib/server/admin-guard';

interface ExportLayer {
	label: string;
	sublabel?: string;
	color: string;
	html: string; // already marked-rendered
}
interface ExportPayload {
	name: string;
	description?: string;
	image: string; // PNG data URL
	layers: ExportLayer[];
}

function esc(s: string): string {
	return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function buildHtml(p: ExportPayload): string {
	const cover = `
		<section class="cover">
			<h1>${esc(p.name)}</h1>
			${p.description ? `<p class="sub">${esc(p.description)}</p>` : ''}
			<img src="${p.image}" alt="" />
			<p class="foot">Generated by DAEDALUS · Parallax &amp; Pixel</p>
		</section>`;

	const pages = p.layers
		.map(
			(l, i) => `
		<section class="layer">
			<div class="bar" style="background:${esc(l.color)}"></div>
			<header>
				<span class="dot" style="background:${esc(l.color)}"></span>
				<h2>${esc(l.label)}</h2>
				${l.sublabel ? `<span class="sub">${esc(l.sublabel)}</span>` : ''}
			</header>
			<div class="body">${l.html}</div>
			<p class="foot">${i + 1} / ${p.layers.length} · ${esc(p.name)}</p>
		</section>`
		)
		.join('');

	return `<!doctype html><html><head><meta charset="utf-8" /><style>
		* { box-sizing: border-box; }
		html, body { margin: 0; padding: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact;
			font-family: 'Inter', ui-sans-serif, system-ui, -apple-system, sans-serif; }
		section { page-break-after: always; position: relative; min-height: 100vh; }
		section:last-child { page-break-after: auto; }
		.cover { background: #050a14; color: #fff; display: flex; flex-direction: column;
			align-items: center; justify-content: center; padding: 2.5cm 2cm; text-align: center; }
		.cover h1 { font-size: 26pt; margin: 0 0 0.3cm; font-weight: 700; }
		.cover .sub { color: rgba(255,255,255,0.6); margin: 0 0 1cm; font-size: 11pt; }
		.cover img { max-width: 100%; max-height: 62%; object-fit: contain; }
		.cover .foot { margin-top: 1cm; color: rgba(255,255,255,0.35); font-size: 8pt;
			letter-spacing: 0.08em; text-transform: uppercase; }
		.layer { padding: 2cm 2.2cm; color: #0f1f33; }
		.layer .bar { position: absolute; top: 0; left: 0; right: 0; height: 0.45cm; }
		.layer header { display: flex; align-items: baseline; gap: 0.3cm; margin: 0.7cm 0 0.5cm; }
		.layer .dot { width: 0.4cm; height: 0.4cm; align-self: center; flex: none; }
		.layer h2 { font-size: 18pt; margin: 0; font-weight: 700; }
		.layer header .sub { color: #64748b; font-size: 10pt; }
		.layer .body { font-size: 11pt; line-height: 1.6; color: #1f2d3d; }
		.layer .body h1, .layer .body h2, .layer .body h3 { font-size: 12pt; margin: 0.5cm 0 0.15cm; }
		.layer .body ul { padding-left: 0.6cm; margin: 0.2cm 0; }
		.layer .body li { margin: 0.08cm 0; }
		.layer .body code { background: #eef2f7; padding: 0.04cm 0.16cm;
			font-family: ui-monospace, monospace; font-size: 9.5pt; }
		.layer .foot { position: absolute; bottom: 1cm; left: 2.2cm; color: #94a3b8; font-size: 8pt; }
	</style></head><body>${cover}${pages}</body></html>`;
}

export const POST: RequestHandler = async ({ request, locals }) => {
	const denied = await requireAdmin(locals);
	if (denied) return denied;

	const payload = (await request.json()) as ExportPayload;
	if (!payload?.image || !Array.isArray(payload.layers)) {
		throw error(400, 'image and layers are required');
	}

	// Chromium may be absent on slim deploy images. resolveChromiumPath() finds a
	// Nix/system binary (or falls back to Playwright's bundled one); if nothing can
	// launch, surface a clear non-5xx "unavailable" response.
	let browser: Awaited<ReturnType<typeof chromium.launch>>;
	try {
		browser = await chromium.launch({
			headless: true,
			executablePath: resolveChromiumPath(),
			args: [
				'--no-sandbox',
				'--disable-setuid-sandbox',
				'--disable-dev-shm-usage',
				'--font-render-hinting=none'
			]
		});
	} catch (e) {
		console.error('[daedalus/export] Chromium failed to launch:', e);
		throw error(503, 'PDF export is unavailable on this server (headless Chromium could not start).');
	}

	try {
		const page = await browser.newPage();
		await page.setContent(buildHtml(payload), { waitUntil: 'networkidle' });
		const pdf = await page.pdf({
			format: 'A4',
			printBackground: true,
			margin: { top: '0', right: '0', bottom: '0', left: '0' }
		});
		return new Response(pdf as BodyInit, {
			headers: {
				'Content-Type': 'application/pdf',
				'Content-Disposition': 'attachment; filename="daedalus-export.pdf"'
			}
		});
	} finally {
		await browser.close();
	}
};
